# Informazioni principali
title: "Apocryphal Nerd Bible from MSN Village"
description: "Atlante digitale di Paola Blondet â€” La Trovatella Digitale"
keywords: "MSN, Atlante, Nerd Bible, Apocryphal Bible, Kernel, Linus Torvalds, EU case T-604/18, Digital Sovereignty, Microsoft, Google, Bibbia Nerd Apocrifa dal Villaggio MSN"
lang: en-US
url: "https://trovatella.github.io"
baseurl: "/-Memorie-dal-Villaggio-MSN"
remote_theme: pages-themes/cayman
markdown: kramdown

# Autore
author: "Paola Blondet"

# Social links
social:
  name: "Trovatella Digitale"
  links:
    - https://github.com/trovatella
    - https://trovatella.github.io/-Memorie-dal-Villaggio-MSN/

# Opzioni
show_downloads: false

# Versione italiana
title_it: "Memorie dal Villaggio MSN - Trovatella"
description_it: "La Bibbia digitale di Paola: liturgie, preghiere e vangeli del Kernel."

# Versione inglese
title_en: "Memories from the MSN Village - Trovatella"
description_en: "Digital Bible of Paola: liturgies, prayers and gospels of the Kernel."

# Plugin per RSS feed
plugins:
  - jekyll-feed
